language: ruby
rvm:
  - 2.4.1

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - ./run.sh build

branches:
  only:
    - master
    - /feat-(.*)/
    - /bug-(.*)/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
    slack: $SLACK_TOKEN
