language: ruby
rvm:
- 2.4.1

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_script:
    - sudo apt-get update -qq && apt-get install -qqy shellcheck

script:
    - shellcheck *.sh
    - ./run.sh build

branches:
  only:
  - master
  - /feat-(.*)/
  - /bug-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
