title: Peli Legacy
url: https://pelilegacy.fi
author: Peliyhdistys Legacy ry
email: toimitus@pelilegacy.fi
description: Peliyhdistys Legacy ry on vuonna 2014 perustettu pelejä ja pelaamista käsitteleviä artikkeleita sekä mediasisältöä toimittava yhdistys.
github_username:  pelilegacy
repository: pelilegacy.github.io
lang: fi
timezone: Europe/Helsinki

# Build settings
strict_front_matter: true
permalink: pretty
theme: minima
date_format: "%d.%m.%Y"
sass:
  style: compressed
plugins:
  - jekyll-feed
exclude:
  - jekyll.log
  - vendor

# Collections
collections:
  podcasts:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: podcasts
    values:
      layout: page
