title: Peli Legacy
email: toimitus@pelilegacy.fi
description: Peliyhdistys Legacy ry:n arkisto
twitter_username: pelilegacy
github_username:  pelilegacy
timezone: Europe/Helsinki

# Build settings
strict_front_matter: true
permalink: pretty
paginate_path: /page/:num
theme: minima
sass:
  style: compressed
gems:
  - jekyll-feed
exclude:
  - run.sh
  - docker-compose.yml
  - .editorconfig
  - nginx
  - jekyll.log
  - Gemfile
  - Gemfile.lock
  - vendor

# Collections
collections:
  podcasts:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: podcasts
    values:
      layout: page
