version: "3.3"

services:
    jekyll:
        image: jekyll/jekyll
        volumes:
            - .:/srv/jekyll
        ports:
            - "80:4000"
        environment:
            BUNDLE_CACHE: "true"
            JEKYLL_ENV: development
        command: bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000
