version: "3.3"

services:
    web:
        image: nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./_site:/var/www/jekyll
        ports:
            - "80:80"
    serve:
        image: jekyll/jekyll
        volumes:
            - .:/srv/jekyll
        ports:
            - "4000:4000"
        environment:
            JEKYLL_ENV: development
        command: jekyll serve
